# Configura��es de conex�o com o PostgreSQL
schemaspy.t=pgsql
schemaspy.host=localhost
schemaspy.port=5432
schemaspy.db=pocgpf
schemaspy.u=admin
schemaspy.p=admin
# Configura��es de sa�da
schemaspy.o=./schemaspy-output
schemaspy.s=public
schemaspy.dp=./drivers
# Op��es de documenta��o
schemaspy.noschema=true
schemaspy.nohtml=false
schemaspy.vizjs=true
# Configura��es de qualidade
schemaspy.rails=true
schemaspy.remarks=true